### PR TITLE
Cw new #120 Delete a post

### PR DESCRIPTION
**Pull request by Cwelshofer**
Adds Option to delete posts on home page and post details
## Description
Same as above..
​
## How do I access this branch?
1. git fetch --all
2. git checkout cw-new
​
## Motivation and Context
We need a delete button !!
## How Has This Been Tested?
works in postman and in client
1. Check that you can delete posts from home page button
2.add more posts to the database if needed to test (you can add them with loaddata in the terminal if you need approved posts)
3.Check and make sure the delete button works on postdetails as well.
​
## Screenshots (if appropriate):
​
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
​
## Checklist:

- [x ] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by egeehartz — CHANGES_REQUESTED** [review]
A user should only be able to delete their own posts, and I was able to delete posts that weren't mine. The delete button should also only show up on the user's own posts and they're showing up for every post on the home page and each post detail..

**Comment by Cwelshofer** [comment]
> A user should only be able to delete their own posts, and I was able to delete posts that weren't mine. The delete button should also only show up on the user's own posts and they're showing up for every post on the home page and each post detail..

>Sorry I'll fix that now..

**Comment by egeehartz** [comment]
in DeleteItem.js, the deleteThisPost function needs to send the user back to home after deleting the post

**Comment by egeehartz** [comment]
I'm also not sure why the onClose is in the deleteThisPost function

**Review by egeehartz — APPROVED** [review]

**Review by esthersanders — APPROVED** [review]

**Pull request merged**
