### PR TITLE
Eh initial

### PR DESCRIPTION
**Pull request by egeehartz**
1. double check with the miro that the file structure is coolio
2. check the providers for each directory to see if it's coolio (with the exception of AuthProvider/UserProvider stuff)

### CODE REVIEW

**Comment by egeehartz** [comment]
also check out the coolio avatar image

**Review by esthersanders — APPROVED** [review]
looks good!

**Comment by stevebrownlee** [comment]
@egeehartz Two things:

1. Please provide a more descriptive title for your pull requests.
1. There is a large amount of commented out code in this PR. That's not acceptable. Please remove commented out code before a PR is submitted.

**Review by stevebrownlee — CHANGES_REQUESTED** [review]
Please remove all commented out code.

**Review by justha — APPROVED** [review]

**Comment by justha** [comment]
see that that profile provider has been removed and added to profiles directory

**Pull request merged**
