### PR TITLE
MyProfile Page Displays User Details & Image

### PR DESCRIPTION
**Pull request by justha**
​
## Description
When the user clicks on My Profile link in NavBar, it displays the user's profile details. 

​
## How do I access this branch?
`git checkout main`
`git fetch --all`
`git checkout hn-MyProfile`

​
## Motivation and Context

​
## How Has This Been Tested?
Confirmed that the active user's details display in browser. 
Confirmed that what displays matches data requested in Postman. 

​
## Screenshots (if appropriate):
​
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
​
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by egeehartz** [comment]
The page doesn't display my user information.
Did you drop, then create a new user table and manually create a new user?
Register doesn't work either.

**Review by esthersanders — COMMENTED** [review]
none of the information is rendering except for the image, and the date which says "invalid date"

**Review by esthersanders — COMMENTED** [review]
when I get all users in postman, I get this error in my terminal:
```
File "/Users/esthersanders/workspace/rare-server-fakes-news/request_handler.py", line 84, in do_GET
    response = get_all_users()
  File "/Users/esthersanders/workspace/rare-server-fakes-news/users/request.py", line 13, in get_all_users
    db_cursor.execute("""
sqlite3.OperationalError: no such column: u.first_name
----------------------------------------
```

**Review by egeehartz — APPROVED** [review]

**Review by esthersanders — APPROVED** [review]

**Comment by justha** [comment]
Added user first and last name to registration form and all user table requests. Ok now.

**Pull request merged**
